In [48]:
import pandas as pd 
import os

In [49]:
def abrir_csv(path, **kwargs):
    data = pd.read_csv(path)
    return data

In [50]:
path = "post_pandemic_remote_work_health_impact_2025.csv"
data = abrir_csv(path)
data.head(10)

,Survey_Date,Age,Gender,Region,Industry,Job_Role,Work_Arrangement,Hours_Per_Week,Mental_Health_Status,Burnout_Level,Work_Life_Balance_Score,Physical_Health_Issues,Social_Isolation_Score,Salary_Range
0,2025-06-01,27,Female,Asia,Professional Services,Data Analyst,Onsite,64,Stress Disorder,High,3,Shoulder Pain; Neck Pain,2,$40K-60K
1,2025-06-01,37,Female,Asia,Professional Services,Data Analyst,Onsite,37,Stress Disorder,High,4,Back Pain,2,$80K-100K
2,2025-06-01,32,Female,Africa,Education,Business Analyst,Onsite,36,ADHD,High,3,Shoulder Pain; Eye Strain,2,$80K-100K
3,2025-06-01,40,Female,Europe,Education,Data Analyst,Onsite,63,ADHD,Medium,1,Shoulder Pain; Eye Strain,2,$60K-80K
4,2025-06-01,30,Male,South America,Manufacturing,DevOps Engineer,Hybrid,65,NaN,Medium,5,NaN,4,$60K-80K
5,2025-06-01,52,Male,Oceania,Customer Service,Business Analyst,Onsite,61,Burnout,Medium,4,Back Pain; Shoulder Pain,3,$60K-80K
6,2025-06-01,50,Female,Asia,Manufacturing,IT Support,Onsite,62,NaN,Medium,4,Back Pain; Shoulder Pain; Wrist Pain,2,$80K-100K
7,2025-06-01,63,Non-binary,Europe,Professional Services,Technical Writer,Onsite,55,Anxiety,High,3,NaN,2,$100K-120K
8,2025-06-01,30,Female,South America,Technology,Software Engineer,Remote,47,Anxiety,Medium,2,Neck Pain,4,$60K-80K
9,2025-06-01,37,Female,Asia,Finance,HR Manager,Onsite,55,Burnout,Medium,5,Back Pain,1,$60K-80K

In [51]:
print(data.columns)

#eliminamos duplicados
data = data.drop_duplicates()

#eliminamos none
data = data.dropna()

#vemos los datos totales
print(len(data))

Index(['Survey_Date', 'Age', 'Gender', 'Region', 'Industry', 'Job_Role',
       'Work_Arrangement', 'Hours_Per_Week', 'Mental_Health_Status',
       'Burnout_Level', 'Work_Life_Balance_Score', 'Physical_Health_Issues',
       'Social_Isolation_Score', 'Salary_Range'],
      dtype='object')
2150

In [52]:
traducimos_columnas = {
'Survey_Date': 'Fecha_de_encuesta',
'Age': 'Edad',
'Gender': 'Género',
'Region': 'Región',
'Industry': 'Industria',
'Job_Role': 'Rol_laboral',
'Work_Arrangement': 'Ubicación_de_trabajo',
'Hours_Per_Week': 'Horas_por_semana',
'Mental_Health_Status': 'Estado_de_salud_mental',
'Burnout_Level': 'Nivel_de_agotamiento',
'Work_Life_Balance_Score': 'Equilibrio_entre_vida_laboral_y_personal',
'Physical_Health_Issues': 'Problemas_de_salud_físico',
'Social_Isolation_Score': 'Puntuación_de_aislamiento_social',
'Salary_Range': 'Rango_salarial',

}
data.rename(columns=traducimos_columnas,inplace=True)

print(data.columns)

Index(['Fecha_de_encuesta', 'Edad', 'Género', 'Región', 'Industria',
       'Rol_laboral', 'Ubicación_de_trabajo', 'Horas_por_semana',
       'Estado_de_salud_mental', 'Nivel_de_agotamiento',
       'Equilibrio_entre_vida_laboral_y_personal', 'Problemas_de_salud_físico',
       'Puntuación_de_aislamiento_social', 'Rango_salarial'],
      dtype='object')

In [ ]:
# Eliminar columnas que no aportan al análisis
data.drop(['Género', 'Industria'], axis=1, inplace=True)
data.head(10)

,Fecha_de_encuesta,Edad,Región,Rol_laboral,Ubicación_de_trabajo,Horas_por_semana,Estado_de_salud_mental,Nivel_de_agotamiento,Equilibrio_entre_vida_laboral_y_personal,Problemas_de_salud_físico,Puntuación_de_aislamiento_social,Rango_salarial
0,2025-06-01,27,Asia,Data Analyst,Onsite,64,Stress Disorder,High,3,Shoulder Pain; Neck Pain,2,$40K-60K
1,2025-06-01,37,Asia,Data Analyst,Onsite,37,Stress Disorder,High,4,Back Pain,2,$80K-100K
2,2025-06-01,32,Africa,Business Analyst,Onsite,36,ADHD,High,3,Shoulder Pain; Eye Strain,2,$80K-100K
3,2025-06-01,40,Europe,Data Analyst,Onsite,63,ADHD,Medium,1,Shoulder Pain; Eye Strain,2,$60K-80K
5,2025-06-01,52,Oceania,Business Analyst,Onsite,61,Burnout,Medium,4,Back Pain; Shoulder Pain,3,$60K-80K
8,2025-06-01,30,South America,Software Engineer,Remote,47,Anxiety,Medium,2,Neck Pain,4,$60K-80K
9,2025-06-01,37,Asia,HR Manager,Onsite,55,Burnout,Medium,5,Back Pain,1,$60K-80K
11,2025-06-01,64,North America,Business Analyst,Remote,35,ADHD,Medium,3,Eye Strain; Wrist Pain,4,$40K-60K
12,2025-06-01,25,Oceania,Data Scientist,Hybrid,57,Burnout,High,2,Back Pain; Eye Strain,1,$80K-100K
13,2025-06-01,37,Europe,UX Designer,Remote,59,Anxiety,High,5,Back Pain; Shoulder Pain; Wrist Pain,5,$60K-80K

In [54]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 2150 entries, 0 to 3156
Data columns (total 12 columns):
 #   Column                                    Non-Null Count  Dtype
---  ------                                    --------------  -----
 0   Fecha_de_encuesta                         2150 non-null   object
 1   Edad                                      2150 non-null   int64
 2   Región                                    2150 non-null   object
 3   Rol_laboral                               2150 non-null   object
 4   Ubicación_de_trabajo                      2150 non-null   object
 5   Horas_por_semana                          2150 non-null   int64
 6   Estado_de_salud_mental                    2150 non-null   object
 7   Nivel_de_agotamiento                      2150 non-null   object
 8   Equilibrio_entre_vida_laboral_y_personal  2150 non-null   int64
 9   Problemas_de_salud_físico                 2150 non-null   object
 10  Puntuación_de_aislamiento_social          2150 non-null   int64
 11  Rango_salarial                            2150 non-null   object
dtypes: int64(4), object(8)
memory usage: 218.4+ KB